import Link from "next/link";
import { Button } from "antd";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative flex flex-col min-h-screen min-w-max bg-gray-100">
        <div className="flex-grow w-full flex justify-center items-center">
          <div className="w-full max-w-md">{children}</div>
        </div>
        <nav className="fixed bottom-0 w-full max-w-md bg-white shadow-md flex justify-around p-3 border-t items-center">
          <Link href="/store/stamp">
            <Button type="text" className="flex-1 text-lg">
              印花
            </Button>
          </Link>
          <div className="h-6 w-px bg-gray-400"></div>
          <Link href="/store/redeem">
            <Button type="text" className="flex-1 text-lg">
              兌換
            </Button>
          </Link>
        </nav>
      </body>
    </html>
  );
}
