// src/app/admin/layout.tsx

import Link from "next/link";
import { Button } from "antd";
import {
  HomeOutlined,
  SettingOutlined,
  UserOutlined,
  GiftOutlined,
} from "@ant-design/icons";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative flex flex-col min-h-screen min-w-max bg-gray-100 pb-16 !bg-gray-100">
        <div className="flex-grow w-full flex justify-center items-center">
          <div className="w-full max-w-md">{children}</div>
        </div>
        <nav className="fixed bottom-0 w-full max-w-md bg-white shadow-md flex justify-around py-4 border-t items-center">
          <Link href="/admin/dashboard">
            <Button
              type="text"
              className="flex-1 text-base flex flex-col items-center gap-0 text-gray-800"
            >
              <HomeOutlined className="text-xl" />
              <span className="mt-0.5">主頁</span>
            </Button>
          </Link>
          <div className="h-6 w-px bg-gray-400"></div>
          <Link href="/admin/stamp_card">
            <Button
              type="text"
              className="flex-1 text-base flex flex-col items-center gap-0 text-gray-800"
            >
              <GiftOutlined className="text-xl" />
              <span className="mt-0.5">印花咭管理</span>
            </Button>
          </Link>
          <div className="h-6 w-px bg-gray-400"></div>
          <Link href="/admin/customer">
            <Button
              type="text"
              className="flex-1 text-base flex flex-col items-center gap-0 text-gray-800"
            >
              <UserOutlined className="text-xl" />
              <span className="mt-0.5">顧客管理</span>
            </Button>
          </Link>
          <div className="h-6 w-px bg-gray-400"></div>
          <Link href="/admin/admin_setting">
            <Button
              type="text"
              className="flex-1 text-base flex flex-col items-center gap-0 text-gray-800"
            >
              <SettingOutlined className="text-xl" />
              <span className="mt-0.5">設定</span>
            </Button>
          </Link>
        </nav>
      </body>
    </html>
  );
}
